### ISSUE TITLE
Unable to get this working when using Parcel bundler

### ISSUE THREAD

**Issue by ko-dever** [hbenl/vscode-firefox-debug#93]
Hi.

I have been trying to get this extension working for almost 3 days, I think I am going to throw my laptop. My problem being : Firefox does not hit my breakpoints, they stay "Unverified". (yes, another one)

My project folder is very simple :
![files](https://user-images.githubusercontent.com/4114656/49053090-8e7b0880-f1e6-11e8-8b90-772223e6a01c.png)

Fresh install of your extension + fresh install of Firefox Developer Edition.

I am using [Parcel](https://github.com/parcel-bundler/parcel) as bundler. The default command to start up a development server [generates source-maps](https://en.parceljs.org/cli.html#disable-source-maps).

I followed your instructions, and checked other issues to see if I could use them to solve mine.. Nothing. But I do understand the problem must be related to path mappings, I am just unable to know what to write, I tried so many things...

My configuration in `launch.json` :
```json
{
  "type": "firefox",
  "request": "launch",
  "name": "Launch ff",
  "url": "http://localhost:1234/",
  "pathMappings": [{
    "url": "http://localhost:1234/",
    "path": "${workspaceFolder}/dist/"
  }],
  "log": {
    "consoleLevel": {
      "PathConversion": "Debug",
      "default": "Error"
    }
  }
},
```

Log from `PathConversion` :
```bash
DEBUG|003.989|PathConversion: Converted url http://localhost:1234/web.9ad09f98.js to path /Users/_my_user_/Dev/game-of-life/dist/web.9ad09f98.js
DEBUG|004.062|PathConversion: Converted url http://localhost:1234/web.e31bb0bc.js to path /Users/_my_user_/Dev/game-of-life/dist/web.e31bb0bc.js
DEBUG|004.063|PathConversion: Sourcemapped path: /Users/_my_user_/Dev/web/index.js
```
The last `Sourcemapped path:` reports an incorrect path, it should be `/Users/_my_user_/Dev/game-of-life/web/index.js`

I also followed the "Loaded Scripts > Right click on a folder > Map to a local directory" but I am not sure to understand why I have 2 entries here, especially the `../../web` that seems to be related to the wrong path reported by `PathConversion` logger:
![loaded scripts](https://user-images.githubusercontent.com/4114656/49053816-98ead180-f1e9-11e8-9369-455699c8db99.png)

On the other hand, I am really surprise that the extension Debugger for Chrome just works perfectly, without any tedious configuration. But I don't want to use it so...

Thanks a lot for any help you can provide !

**Comment by rugk** [comment]
Do you by instance use ES6 modules?

**Comment by ko-dever** [comment]
> Do you by instance use ES6 modules?

@rugk 
We can use this feature with Parcel, but in this project I don't, my `index.js` is as simple as that :

```js
'use strict';

const foo = 'foo'; // breakpoint-ed

// console.warn( new Date() );

const bar = 'bar'; // breakpoint-ed
console.log( bar );
```

**Comment by hbenl** [comment]
That was a bug - I didn't handle the relative path in the sourcemap (that's why you saw `../../web` in the Loaded Scripts Explorer). I just published a new version containing the fix, with this version my test project works with
```
  "url": "http://localhost:1234/",
  "webRoot": "${workspaceFolder}"
```
and without any `pathMappings`.

**Comment by ko-dever** [comment]
It seems a bit better now, at least some breakpoints are hit, thank you !

I say "some" because I still have a lot of issues, breakpoints moved or not hit, debugger paused somewhere else, browser stuck due to some settings (`reAttach` for example) ... Its operation is too random in my case.

**Comment by high1** [comment]
I'm still seeing this. A simple project that uses React and Typescript does not work. All the proje whct files are in src subfolder, the index.html just directly loads index.tsx script which simply renders a component to the DOM. WIth 
 "url": "http://localhost:1234/",
  "webRoot": "${workspaceFolder}"
I get this in console:
 Converted url http://localhost:1234/node_modules/react/index.js to path E:\dev\react\parcel-test\localhost:1234\node_modules\react\index.js (the right path is the one without localhost:1234.
This configuration:
 "name": "Firefox localhost",
            "type": "firefox",
            "request": "launch",
            "url": "http://localhost:1234",
            "pathMappings": [{
                "url": "http://localhost:1234",
                "path": "${workspaceFolder}"
            }]
shows correct paths, and breakpoints are verified, but not hit... 
This is something that looks wrong to me, from the log:
SourceMappingSourceActorProxy: Computing generated location for http://localhost:1234/src/ts/index.tsx:5:undefined
SourceActorProxy: Breakpoint has been set at undefined in http://localhost:1234/ts.b6d0f0dc.js
not sure if this is helpfull, the project is really simple, seems to me that it should work...
Attaching the log, if you want the source, it's few kilobytes, so just say... Or is something missing in my config?
[log.txt](https://github.com/hbenl/vscode-firefox-debug/files/2700830/log.txt)
